<?php
/*
Plugin Name: Storm Debug Development Backtraces
Description: Display debug backtraces for every error generated by PHP. This includes E_STRICT and E_ALL so contains many more errors than you might expect. This is useful for finding and debugging issues during development, but could easily break your markup, and is not for users who are not editing code directly. Requires jQuery to be included with your theme.
Version: 0.1
Author: Storm Consultancy
Author URI: http://www.stormconsultancy.co.uk
License: GPL2
*/

set_error_handler('error_backtrace');

function error_backtrace($errno, $errstr, $errfile, $errline, $errcontext) {
  echo '<br />';
  echo '<a href="#" onclick="jQuery(this).next().css(\'display\',\'block\'); jQuery(this).next().next().css(\'display\',\'block\'); jQuery(this).css(\'display\',\'none\'); return false;">Show Backtrace For Error</a>';
  echo '<a href="#" style="display:none" onclick="jQuery(this).prev().css(\'display\',\'block\'); jQuery(this).next().css(\'display\',\'none\'); jQuery(this).css(\'display\',\'none\'); return false;">Hide Backtrace</a>';
  echo '<div style="display:none; font-size: 10px; background-color: #F5F6CE; padding-left: 5px; padding-right: 5px; overflow: auto; border-radius: 5px;">';
  echo '<pre>';
  debug_print_backtrace();
  echo '</pre>';
  echo '</div>';
  return false;
}

?>
